
  name: i3lock
  version: '0.1'
  summary: i3lock is a simple screen locker like slock
  description: |
    i3lock is a simple screen locker like slock.
    After starting it, you will see a white screen (you can configure the color/an image).
    You can return to your screen by entering your password.

  grade: stable
  confinement: strict

  apps:
    i3lock:
      command: i3lock
      plugs:
        - process-control
        - x11
        - account-control

  parts:
    i3lock:
      source: .
      plugin: autotools
      prepare: autoreconf -fi
      build-packages:
        - pkg-config
        - libpam0g-dev
        - libcairo2-dev
        - libxcb1-dev
        - libxcb-dpms0-dev
        - libxcb-image0-dev
        - libxcb-util0-dev
        - libev-dev
        - libxcb-xinerama0-dev
        - libxcb-xkb-dev
        - libxcb-randr0-dev
        - libxkbcommon-x11-dev
        - libxkbcommon-dev
